cargo-features = ["profile-rustflags"]

[package]
name = "smallvec-bound2-lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
path = "lib.rs"

[dependencies]
libc = "0.2"
cfg-if = "0.1.10"

[dependencies.verifier]
path = "../../verifier/src"
default-features = false
# panic_error also implies no_std
features = ["panic_error"]

[dependencies.smallvec]
version = "1.10.0"
features = ["const_new"]

[dependencies.sea]
path = "../../sea-lib"
default-features = false
features = []

[features]
default = []  # Specify other default features here, if any        

